import type { RepoAnalysis } from './analyzer.js';

export function generateDesign(analysis: RepoAnalysis): string {
    const { projectName, techStack, structure, projectType } = analysis;

    const date = new Date().toLocaleDateString();

    let mermaidDiagram = 'graph TD;\n';
    mermaidDiagram += '    User((User))\n';

    if (projectType === 'Frontend') {
        mermaidDiagram += '    User --> Client[Frontend UI]\n';
        // If we detected API calls (future feature), we could add them
    } else if (projectType === 'Backend') {
        mermaidDiagram += '    User --> API[API Gateway / Server]\n';
        if (techStack.includes('MongoDB') || techStack.includes('PostgreSQL')) {
            mermaidDiagram += '    API --> DB[(Database)]\n';
        }
    } else if (projectType === 'Fullstack') {
        mermaidDiagram += '    User --> Client[Frontend]\n';
        mermaidDiagram += '    Client --> Server[Backend Server]\n';
        if (techStack.includes('MongoDB') || techStack.includes('PostgreSQL') || techStack.includes('Prisma')) {
            mermaidDiagram += '    Server --> DB[(Database)]\n';
        }
    } else {
        mermaidDiagram += '    User --> System[System]\n';
    }

    // Add styles
    mermaidDiagram += '    classDef plain fill:#fff,stroke:#333,stroke-width:1px;\n';
    mermaidDiagram += '    class User,Client,Server,API,DB,System plain;\n';


    return `# System Design: ${projectName}
Generated on: ${date}

## 1. Project Overview
**Type:** ${projectType}

This system design document was automatically generated based on the repository structure and dependencies.

## 2. Technology Stack
| Category | Technologies |
|----------|--------------|
| **Detected** | ${techStack.join(', ') || 'None detected'} |

## 3. High-Level Architecture
The following diagram illustrates the high-level architecture of the system.

\`\`\`mermaid
${mermaidDiagram}
\`\`\`

## 4. Folder Structure
The high-level structure of the repository is as follows:

\`\`\`
${structure.map(s => `- ${s}`).join('\n')}
\`\`\`

## 5. Deployment / Infrastructure
${techStack.includes('Docker') ? '- **Docker**: Containerization is used.' : ''}
${techStack.includes('Docker Compose') ? '- **Docker Compose**: Multi-container orchestration is setup.' : ''}

---
*Generated by System Design Generator*
`;
}
